gantt
    title Этап 2. Масштабирование (Октябрь 2026 — Март 2028)
    dateFormat YYYY-MM
    axisFormat %b %Y
    section Платформа
        Масштабирование платформенных сервисов: 2026-10, 120d
        Внедрение инструментов контроля качества данных: 2027-01, 90d
    section Домены
        Подключение всех доменов и новых направлений: 2026-11, 150d
        Разработка событийных потоков и витрин: 2027-02, 180d
    section Self-service
        Расширение портала и обучение BI-аналитиков: 2027-01, 180d
    section Legacy
        Внедрение антикоррупционных слоёв: 2026-11, 180d
        Вывод устаревших интеграций: 2027-06, 120d