gantt
    title Этап 3. Оптимизация и поддержка (Апрель 2028 — Март 2029)
    dateFormat YYYY-MM
    axisFormat %b %Y
    section Платформа
        Переход на near-real-time аналитику: 2028-04, 240d
        Автоматизация governance и контроля качества: 2028-06, 300d
    section Домены
        Самостоятельное развитие Data Product доменными командами: 2028-10, 540d
    section Расширение
        Подключение новых регионов: 2028-07, 300d
    section Legacy
        Полный вывод DWH и ESB из эксплуатации: 2028-09, 240d